@startuml

start

:Подача заявки на получение книги;

:Проверка на наличие этой книги\nв архиве клуба;

if (Книга есть в наличии?) then (да)
  :Подтверждение получения книги;
  :Внесение данных студента\nв базу данных;
  :Внесение данных о взятой книге\nв базу данных;
  stop
else (нет)
  :Отказ в получении книги;
  stop
endif

@enduml
