@startuml

start

:Подача заявки на возврат книги;

:Загрузка фото для оценки\nсостояния книги;

if (Книга в хорошем состоянии?) then (да)
  :Удаление данных студента\nиз базы данных;
  :Смена статуса книги\nна "в наличии";
  :Книга успешно возвращена;
  stop
else (нет)
  :Штраф;
  :Выписка предупреждения студенту;
  if (У студента уже есть\n3 предупреждения?) then (да)
    :Исключение из литературного клуба;
    stop
  else (нет)
    :Книга успешно возвращена;
    stop
  endif
endif

@enduml
